### ISSUE TITLE
invalid literal for int()  influxDP Port

### ISSUE THREAD

**Issue by wallacj** [bolausson/SensorPush#1]
This is probably me not understanding the format of the config file
can you provide me some guidance?

thanks
j

**Comment by bolausson** [comment]
Hej,

it should look like this:

`[SONSORPUSHAPI]
LOGIN = you@example.com
PASSWD = your-example-password


[INFLUXDBCONF]
IFDB_USER = influxdb-user-name
IFDB_PW = influxdb-user-password
IFDB_IP = localhost
IFDB_PORT = 8086
IFDB_DB = influxdb-database-name
`
Instead of localhost you can also add the IP of the host running your InfluxDB.

**Comment by wallacj** [comment]
thanks that seems to have taken care of it.
I appreciate the help.
