### ISSUE TITLE
Pressure parsing error

### ISSUE THREAD

**Issue by canada7764** [bolausson/SensorPush#3]
Hello,
 
 The script might be parsing the SensorPush API response incorrectly, resulting in the "pressure" field being treated as a string instead of a float or something else.  Appreciated the help.

`Iterations required: 3'
'-------------------------------------------------------------------'
'Iteration 1/3'
'Request truncated: False'
'Number of samples fetched: 60'
'Number of sensors queried: 6'
''
'##################Somthing went wrong################'
'~~~~~~~~~~~~Exception~~~~~~~~~~~~~'
InfluxDBClientError('400: {"error":"partial write: field type conflict: input field \\"pressure\\" on measurement \\"SensorPush\\" is type float, already exists as type string dropped=10"}')
'~~~~~~~~~~~~Request status code~~~~~~~~~~~~~'
200
`

**Comment by bolausson** [comment]
Hello @canada7764,

this error indicates, that the first value which was written to your InfluxDB was of "type string" and the value you are now trying to write is of "type float". Since you can't write mixed types into the same time series, you are seing this message.

To fix this, you must delete your entire "pressure" time series.

I just comitted sensorpush2.py which uses InfluxDB2 and contains some improvemnts when it comes to the type of values.
(essentially I now enforce a type when storing the value in the dict which his written to InfluxDB).

I think you issue is an result from a mistake I have made here:
https://github.com/bolausson/SensorPush/blob/b5fb69667989a4f5796aa8935a9a71759c9b0f66/sensorpush.py#L531
Here I define pressure as empty string if the sensor doesn't return a value.

A quick fix would be to set it to 0.0 instead of "":
`pressure = 0.0`
or to be dead sure:
`pressure = float(0.0)`

You could do the same for all other variables in the dictionary. Just wrap all values in float() e.g.:
 

>                    measurement.extend([
>                         {
>                             'measurement': 'SensorPush',
>                             'tags': {
>                                 'sensor_id': float(key),
>                                 'sensor_name': str(sensors[key]['name']),
>                             },
>                             'fields': {
>                                 'temperature': float(temperature),
>                                 'humidity': float(humidity),
>                                 'pressure': float(pressure),
>                                 'altitude': float(altitude),
>                                 'dewpoint': float(dewpoint),
>                                 'vpd': float(vpd),
>                                 'abs_humidity': float(abs_humidity)
>                             },
>                             'time': observed
>                         }
>                     ])

The dictionaries in sensorpush.py defined here:
https://github.com/bolausson/SensorPush/blob/b5fb69667989a4f5796aa8935a9a71759c9b0f66/sensorpush.py#L564

Or you can give sensorpush2.py a try which no longer creates the time series for a device if the device does not return the value.

Let me know if the above fixed the issue for you, then I might add the fix to senorpush.py.
I recommend to test sensorpush2.py as I will not continue to maintain sensorpush.py (which uses InfluxDB 1.x)

Cheers,
Bjoern
